# Generated by Django 3.2.8 on 2022-07-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_post_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
