# Generated by Django 3.2.8 on 2022-07-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_rename_notifications_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_tyoe',
            new_name='notification_type',
        ),
    ]
