# Generated by Django 3.2.8 on 2022-08-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_rename_notification_tyoe_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
