# Generated by Django 3.2.8 on 2022-08-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.CharField(default='Todas as idades', max_length=70),
        ),
        migrations.AddField(
            model_name='post',
            name='music',
            field=models.CharField(default='Todos os géneros', max_length=70),
        ),
    ]
