# Generated by Django 3.2.8 on 2022-08-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_auto_20220828_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='age',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='music',
            field=models.CharField(default='', max_length=70),
        ),
    ]
