# Generated by Django 3.2.8 on 2022-08-31 05:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0021_post_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
