# Generated by Django 3.2.8 on 2022-08-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_auto_20220831_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
