# Generated by Django 3.2.8 on 2022-09-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_alter_userprofile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
