# Generated by Django 3.2.8 on 2022-09-06 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0027_post_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ratings',
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
