# Generated by Django 3.2.8 on 2022-09-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0028_auto_20220906_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
    ]
