# Generated by Django 3.2.8 on 2022-09-06 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0030_post_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fav',
        ),
        migrations.AddField(
            model_name='post',
            name='favs',
            field=models.ManyToManyField(blank=True, related_name='favs', to=settings.AUTH_USER_MODEL),
        ),
    ]
