# Generated by Django 3.2.8 on 2022-09-07 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0032_post_likes_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
