# Generated by Django 4.1.1 on 2022-09-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0033_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
