# Generated by Django 4.1.1 on 2022-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0034_alter_post_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favs_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
