# Generated by Django 4.1.1 on 2022-09-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0035_userprofile_favs_count_userprofile_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='convidados',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convidados', to='social.userprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
