# Generated by Django 4.1.1 on 2022-09-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0037_product_file_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default="2002-09-03"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=40),
        ),
    ]
