# Generated by Django 4.1.1 on 2022-09-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0037_userprofile_customer_userprofile_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
