# Generated by Django 4.1.1 on 2022-09-28 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0038_post_public_userprofile_birthday_userprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default=datetime.date(2022, 9, 28)),
        ),
    ]
