# Generated by Django 4.1.1 on 2022-09-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0040_alter_userprofile_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birthday',
            new_name='birth',
        ),
    ]
