# Generated by Django 4.1.1 on 2022-09-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0041_rename_birthday_userprofile_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(default='2002-09-03'),
        ),
    ]
