# Generated by Django 4.1.1 on 2022-09-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0042_alter_userprofile_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
